//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Login_open.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Login_open.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _11zon_resized_18_ {
            get {
                object obj = ResourceManager.GetObject("11zon_resized(18)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _11zon_resized_19_ {
            get {
                object obj = ResourceManager.GetObject("11zon_resized(19)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _11zon_resized_20_ {
            get {
                object obj = ResourceManager.GetObject("11zon_resized(20)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _28_3840x2160_desktop_4k_grand_theft_auto_san_andreas_wallpaper_1_ {
            get {
                object obj = ResourceManager.GetObject("28-3840x2160-desktop-4k-grand-theft-auto-san-andreas-wallpaper(1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _28_3840x2160_desktop_4k_grand_theft_auto_san_andreas_wallpaper_1_1 {
            get {
                object obj = ResourceManager.GetObject("28-3840x2160-desktop-4k-grand-theft-auto-san-andreas-wallpaper(1)1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap AAAAQQi0w_nNYvxL1q7tan_0bN3gZJNri6zP_1Sdx3dNmmguTecs94PDkDO1VW_uYK8M_dLH0wVt93BYZP8tSGKNxU20BPZiv2H4aTqQEBZE_MMjFQ56O1o1asNiy0fEozYT90gLd42BAkKTyDppqWBDH9SCq3Q {
            get {
                object obj = ResourceManager.GetObject("AAAAQQi0w_nNYvxL1q7tan-0bN3gZJNri6zP-1Sdx3dNmmguTecs94PDkDO1VW-uYK8M-dLH0wVt93BYZ" +
                        "P8tSGKNxU20BPZiv2H4aTqQEBZE_MMjFQ56O1o1asNiy0fEozYT90gLd42BAkKTyDppqWBDH9SCq3Q", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap apps_65175_66515090704019777_c95568d5_8811_4e30_a0f2_3ac354b35880 {
            get {
                object obj = ResourceManager.GetObject("apps.65175.66515090704019777.c95568d5-8811-4e30-a0f2-3ac354b35880", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap artworks_6KQzmTbNrTV2k054_y55Jgw_t500x500 {
            get {
                object obj = ResourceManager.GetObject("artworks-6KQzmTbNrTV2k054-y55Jgw-t500x500", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap big_smoke_and_ryder_gta_sa_artwork_by_marmakar_dgmdycp_fullview {
            get {
                object obj = ResourceManager.GetObject("big_smoke_and_ryder_gta_sa_artwork_by_marmakar_dgmdycp-fullview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap big_smoke_and_ryder_gta_sa_artwork_by_marmakar_dgmdycp_fullview1 {
            get {
                object obj = ResourceManager.GetObject("big_smoke_and_ryder_gta_sa_artwork_by_marmakar_dgmdycp-fullview1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap f6ue5tl05q881 {
            get {
                object obj = ResourceManager.GetObject("f6ue5tl05q881", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap free_rockstar_logo_icon_download_in_svg_png_gif_file_formats__games_company_brand_world_logos_vol_9_pack_icons_282963 {
            get {
                object obj = ResourceManager.GetObject("free-rockstar-logo-icon-download-in-svg-png-gif-file-formats--games-company-brand" +
                        "-world-logos-vol-9-pack-icons-282963", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap gta_5_theme_pj15 {
            get {
                object obj = ResourceManager.GetObject("gta-5-theme-pj15", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap gta_san_andreas_background_6fz9tt0ivo7irsjj {
            get {
                object obj = ResourceManager.GetObject("gta-san-andreas-background-6fz9tt0ivo7irsjj", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GTA_San_Andreas_Cheats {
            get {
                object obj = ResourceManager.GetObject("GTA-San-Andreas-Cheats", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
